# POS Printer WinUSB Driver Installer v4.0
# Uses libwdi (same as Zadig) for GUARANTEED driver installation
# Run as Administrator

$ErrorActionPreference = "SilentlyContinue"

# Colors
function Write-Success { param($msg) Write-Host $msg -ForegroundColor Green }
function Write-Info { param($msg) Write-Host $msg -ForegroundColor Cyan }
function Write-Warn { param($msg) Write-Host $msg -ForegroundColor Yellow }
function Write-Err { param($msg) Write-Host $msg -ForegroundColor Red }

# Check admin
function Test-Administrator {
    $currentUser = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($currentUser)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

# Get USB devices
function Get-USBPrinters {
    $printers = @()
    $usbDevices = Get-PnpDevice -Class USB, Printer, USBDevice, SoftwareDevice -Status OK -ErrorAction SilentlyContinue

    foreach ($device in $usbDevices) {
        $instanceId = $device.InstanceId
        if ($instanceId -match "USB\\VID_([0-9A-F]{4})&PID_([0-9A-F]{4})") {
            $printers += [PSCustomObject]@{
                Name = $device.FriendlyName
                InstanceId = $instanceId
                VID = $matches[1]
                PID = $matches[2]
                Class = $device.Class
            }
        }
    }
    return $printers
}

# Download libwdi installer
function Get-DriverInstaller {
    $installerDir = "$env:TEMP\pos-driver-installer"
    $installerExe = "$installerDir\qmk_driver_installer.exe"

    if (Test-Path $installerExe) {
        return $installerExe
    }

    Write-Info "Downloading driver installer (libwdi)..."

    New-Item -ItemType Directory -Path $installerDir -Force | Out-Null

    $zipUrl = "https://github.com/qmk/qmk_driver_installer/releases/download/v1.01/qmk_driver_installer.zip"
    $zipPath = "$env:TEMP\qmk_driver_installer.zip"

    try {
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-WebRequest -Uri $zipUrl -OutFile $zipPath -UseBasicParsing -ErrorAction Stop

        # Extract
        Expand-Archive -Path $zipPath -DestinationPath $env:TEMP -Force

        # Move exe to our directory
        Copy-Item "$env:TEMP\qmk_driver_installer\qmk_driver_installer.exe" $installerExe -Force

        Write-Success "  Downloaded successfully!"
        return $installerExe
    } catch {
        Write-Err "  Failed to download: $_"
        return $null
    }
}

# Create driver config file
function New-DriverConfig {
    param(
        [string]$DeviceName,
        [string]$VID,
        [string]$ProductId
    )

    # Generate a unique GUID for this device
    $guid = [guid]::NewGuid().ToString()

    # Clean device name (remove special chars that could cause issues)
    $cleanName = $DeviceName -replace '[,;]', ' '

    # Create a recognizable name that keeps the original identity
    $displayName = "POS $cleanName (WebUSB)"

    $configContent = @"
# WinUSB driver configuration for POS Printer
# Generated by ngx-pos-print driver installer
winusb,$displayName,$VID,$ProductId,$guid
"@

    $configPath = "$env:TEMP\pos-driver-installer\drivers.txt"
    $configContent | Out-File -FilePath $configPath -Encoding ASCII
    return $configPath
}

# Main
Clear-Host
Write-Host ""
Write-Host "========================================" -ForegroundColor Magenta
Write-Host "  POS Printer WinUSB Driver Installer  " -ForegroundColor Magenta
Write-Host "        for ngx-pos-print v4.0         " -ForegroundColor Magenta
Write-Host "       (Powered by libwdi/Zadig)       " -ForegroundColor Magenta
Write-Host "========================================" -ForegroundColor Magenta
Write-Host ""

# Check admin
if (-not (Test-Administrator)) {
    Write-Err "This script requires Administrator privileges."
    Write-Info "Right-click and select 'Run as Administrator'"
    Read-Host "Press Enter to exit"
    exit 1
}

Write-Success "Running as Administrator."
Write-Host ""

# Scan devices
Write-Info "Scanning USB devices..."
$devices = Get-USBPrinters

if ($devices.Count -eq 0) {
    Write-Warn "No USB devices found. Connect your printer and try again."
    Read-Host "Press Enter to exit"
    exit 0
}

# Display
Write-Host ""
Write-Info "Found $($devices.Count) USB device(s):"
Write-Host ""
Write-Host "  #  | VID:PID     | Class           | Name" -ForegroundColor White
Write-Host "  ---|-------------|-----------------|--------------------------------" -ForegroundColor Gray

$index = 1
foreach ($device in $devices) {
    $classDisplay = if ($device.Class) { $device.Class.PadRight(15).Substring(0,15) } else { "Unknown".PadRight(15) }
    $nameDisplay = if ($device.Name) { $device.Name } else { "Unknown Device" }

    if ($device.Class -eq "USBDevice") {
        $color = "Green"
        $status = "(WinUSB OK)"
    } elseif ($device.Name -like "*Printer*" -or $device.Name -like "*POS*") {
        $color = "Yellow"
        $status = "(NEEDS WINUSB)"
    } else {
        $color = "White"
        $status = ""
    }

    Write-Host ("  {0,-2} | {1}:{2} | {3} | {4} {5}" -f $index, $device.VID, $device.PID, $classDisplay, $nameDisplay, $status) -ForegroundColor $color
    $index++
}

Write-Host ""
Write-Warn "Yellow = Needs WinUSB"
Write-Success "Green  = Already OK"
Write-Host ""

# Select device
$selection = Read-Host "Enter device number (or 'q' to quit)"

if ($selection -eq 'q') { exit 0 }

$selectedIndex = [int]$selection - 1
if ($selectedIndex -lt 0 -or $selectedIndex -ge $devices.Count) {
    Write-Err "Invalid selection."
    Read-Host "Press Enter to exit"
    exit 1
}

$selected = $devices[$selectedIndex]
Write-Host ""
Write-Info "Selected: $($selected.Name)"
Write-Info "VID:PID:  $($selected.VID):$($selected.PID)"
Write-Info "Class:    $($selected.Class)"

if ($selected.Class -eq "USBDevice") {
    Write-Host ""
    Write-Success "Already has WinUSB! Try unplugging/replugging if WebUSB doesn't work."
    Read-Host "Press Enter to exit"
    exit 0
}

# Confirm
Write-Host ""
Write-Warn "This will install WinUSB driver for this device."
$confirm = Read-Host "Continue? (y/n)"
if ($confirm -ne 'y' -and $confirm -ne 'Y') { exit 0 }

# Download installer
Write-Host ""
$installer = Get-DriverInstaller
if (-not $installer) {
    Write-Err "Could not download driver installer."
    Read-Host "Press Enter to exit"
    exit 1
}

# Create config
Write-Info "Creating driver configuration..."
$configPath = New-DriverConfig -DeviceName $selected.Name -VID $selected.VID -ProductId $selected.PID
Write-Success "  Config: $configPath"

# Install driver
Write-Host ""
Write-Info "Installing WinUSB driver (this may take a moment)..."
Write-Warn "A Windows security prompt may appear - click 'Install' to continue."
Write-Host ""

$installerDir = Split-Path $installer -Parent
Push-Location $installerDir

try {
    # Run the installer with --force to install even if device not currently connected
    $process = Start-Process -FilePath $installer -ArgumentList "--force", "drivers.txt" -Wait -PassThru -NoNewWindow

    if ($process.ExitCode -eq 0) {
        Write-Host ""
        Write-Success "Driver installation command completed."
    } else {
        Write-Warn "Installer returned code: $($process.ExitCode)"
    }
} catch {
    Write-Err "Error running installer: $_"
}

Pop-Location

# Wait for device to re-enumerate
Write-Host ""
Write-Info "Waiting for device to re-enumerate..."
Start-Sleep -Seconds 5

# Verify
Write-Info "Verifying installation..."
$newDevice = Get-PnpDevice | Where-Object {
    $_.InstanceId -like "*VID_$($selected.VID)*PID_$($selected.PID)*" -and
    $_.Status -eq "OK"
} | Select-Object -First 1

Write-Host ""
if ($newDevice -and $newDevice.Class -eq "USBDevice") {
    Write-Success "========================================"
    Write-Success "       SUCCESS! WinUSB INSTALLED        "
    Write-Success "========================================"
    Write-Host ""
    Write-Success "Your printer is ready for WebUSB!"
    Write-Host ""
    Write-Info "Next steps:"
    Write-Host "  1. Unplug and replug your printer" -ForegroundColor White
    Write-Host "  2. Open Chrome/Edge" -ForegroundColor White
    Write-Host "  3. Test with ngx-pos-print" -ForegroundColor White
} elseif ($newDevice) {
    Write-Host "Device found but class is: $($newDevice.Class)" -ForegroundColor Yellow
    Write-Host ""
    Write-Warn "Driver may not have been applied."
    Write-Info "Try unplugging and replugging your printer."
    Write-Host ""
    Write-Info "If it still doesn't work, please:"
    Write-Host "  1. Unplug the printer" -ForegroundColor White
    Write-Host "  2. Run this installer again" -ForegroundColor White
    Write-Host "  3. Replug the printer" -ForegroundColor White
} else {
    Write-Warn "Device not detected. Please replug your printer."
}

Write-Host ""
Read-Host "Press Enter to exit"
